version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/mybuild
permissions:
  - object: /home/ubuntu/mybuild
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: ~/restart.sh
      timeout: 60