on:
  # 직접 실행
  workflow_dispatch:
  # push 됐을 때
  push:
    branches:
      [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check-Out
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Test
        run: ./gradlew test


  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check-Out
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew clean build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync \
          --region ap-northeast-2 \
          build s3://spring-githubaction-bucket \
          --delete \
          aws s3 cp s3://spring-githubaction-bucket/libs/github-action-test-ci-cd-0.0.1-SNAPSHOT.jar \
          /home/ubuntu/
