on:
  # 직접 실행
  workflow_dispatch:
  # push 됐을 때
  push:
    branches:
      [ main ]

jobs:
  #  test:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Check-Out
  #        uses: actions/checkout@v3
  #
  #      - name: Set up JDK 17
  #        uses: actions/setup-java@v3
  #        with:
  #          java-version: '17'
  #          distribution: 'zulu'
  #
  #      - name: Grant execute permission for gradlew
  #        run: chmod +x ./gradlew
  #
  #      - name: Run Test
  #        run: ./gradlew test


  deploy:
    #    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check-Out
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

#      - name: Build project
#        run: ./gradlew clean build -x test

      - name: Make Zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: |
          aws s3 sync \
          --region ap-northeast-2 \
          build s3://spring-githubaction-bucket/$GITHUB_SHA.zip \

      - name: Deploy to EC2 From S3
        run:
          aws deploy create-deployment
          --application-name github-action
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name my-codedeploy-group
          --s3-location bucket=spring-githubaction-bucket,bundleType=zip,key=$GITHUB_SHA.zip
