on:
  # 직접 실행
  workflow_dispatch:
  # push 됐을 때
  push:
    branches:
      [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check-Out
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Test
        run: ./gradlew test